### ISSUE TITLE
`cloudflare:` modules cause dev errors

### ISSUE THREAD

**Issue by dario-piotrowicz** [flarelabs-net/vite-plugin-cloudflare#47]
When running `dev` and importing `cloudflare:` modules, everything works find but we get a warning/error in the terminal  saying that the module could not be resolved

For example this is what we get when running `pnpm dev` in the [`external-durable-object` playground app](https://github.com/flarelabs-net/vite-plugin-cloudflare/tree/main/playground/external-durable-objects):
![Screenshot 2024-11-04 at 15 51 13](https://github.com/user-attachments/assets/f74e603f-82bc-4b09-8815-9e1f41b2a2d1)

**Comment by jamesopstad** [comment]
I think this is because with pre-bundling they now also need to be added here:

https://github.com/flarelabs-net/vite-plugin-cloudflare/blob/7adf439fbd5e187c7419fe5686ed653191363d87/packages/vite-plugin-cloudflare/src/cloudflare-environment.ts#L140

**Comment by dario-piotrowicz** [comment]
> I think this is because with pre-bundling they now also need to be added here:
> 
> https://github.com/flarelabs-net/vite-plugin-cloudflare/blob/7adf439fbd5e187c7419fe5686ed653191363d87/packages/vite-plugin-cloudflare/src/cloudflare-environment.ts#L140-L142

yeah it was just that 👍
