### ISSUE TITLE
`DurableObject.name` produces different results in preview and dev

### ISSUE THREAD

**Issue by dario-piotrowicz** [flarelabs-net/vite-plugin-cloudflare#81]
The following code:
```ts
import { DurableObject } from 'cloudflare:workers';

console.log(DurableObject.name);
```

outputs `DurableObject` when run in dev mode and `DurableObjectBase` when run in preview (and I assume production?)

We need to investigate which of these two is the correct output and understand why we get the other and if we can realign the two

**Comment by dario-piotrowicz** [comment]
Ok, the correct value is `DurableObject` (without the `Base` suffix)

Since that's what we get with `wrangler dev`:
![Screenshot 2024-12-02 at 14 54 35](https://github.com/user-attachments/assets/1f8be69e-de9e-4ccf-b9b0-2a2e9c5237c6)

and even `deploy`:
![Screenshot 2024-12-02 at 14 56 16](https://github.com/user-attachments/assets/97881e20-85f7-4cf2-af81-4bc0ca43b151)

**Comment by dario-piotrowicz** [comment]
mh.... ok I am not sure this really seems like a bit of a weird one.... it's also a workerd quirk from what I can tell

([internal discussion](https://chat.google.com/room/AAAAnS2bXT4/0Wk4Hmm8If4/0Wk4Hmm8If4?cls=10))

**Comment by jamesopstad** [comment]
From the discussion, it seems this isn't something unique to our plugin. Shall we close this one?

**Comment by dario-piotrowicz** [comment]
> From the discussion, it seems this isn't something unique to our plugin. Shall we close this one?

yeah I think this might be something we'll just have to live with 😕
