### ISSUE TITLE
In the module resolution playground app the react import works during dev but not build

### ISSUE THREAD

**Issue by dario-piotrowicz** [flarelabs-net/vite-plugin-cloudflare#82]
If you run the module resolution playground app in dev mode everything seems to be working fine

But if you run it in preview mode and fetch from `/third-party/react` you get the following error:
![Screenshot 2024-12-02 at 10 19 31](https://github.com/user-attachments/assets/9030bea3-e631-4554-804c-f25d96e86a4f)

(which is something we've seen in the past: https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/22)

Something is not adding up here to me, because in the module resolution app I don't see us opting in nodejs_compat anywhere, so should this issue not be present for `dev` as well?

Additionally if I add
```
compatibility_flags = ['nodejs_compat']
```
to the `wrangler.toml` file, then both for dev and build the app breaks completely erroring that the `unenv/runtime/node/process/$cloudflare` module can't be found

**Comment by jamesopstad** [comment]
> Additionally if I add
> 
> ```
> compatibility_flags = ['nodejs_compat']
> ```
> 
> to the `wrangler.toml` file, then both for dev and build the app breaks completely erroring that the `unenv/runtime/node/process/$cloudflare` module can't be found

You need to add `unenv` as a dependency if you use `nodejs_compat` in one of the playgrounds. I remember @petebacondarwin saying that this is just a quirk of it being in a monorepo with the plugin package. We should verify that this isn't necessary when using the published package.

**Comment by dario-piotrowicz** [comment]
This is the problematic piece of code: [react code](https://github.com/facebook/react/blob/1c9b138714a69cd136a3d82769b1fd9a4b318953/packages/react/npm/index.js#L3)

Without `nodejs_compat` (which I don't think should be needed for react)

In dev, in the pre-bundled react file `process.env.NODE_ENV === 'production'` is already resolved for `false`:
![Screenshot 2024-12-05 at 11 11 05](https://github.com/user-attachments/assets/7aa7d0b6-4dd1-44cd-8b05-bfba54118314)

But in the built output it is not:
![Screenshot 2024-12-05 at 11 14 48](https://github.com/user-attachments/assets/b8745a76-a338-4659-b533-5e908e21dae2)

which explains why we are encountering the problem for build but not for dev

So what I need to do now is understanding why rollup doesn't resolve `process.env.NODE_ENV === 'production'` to `true`, as I assume it should do 🤔

**Comment by dario-piotrowicz** [comment]
Ok I think this sums up the rollup issue quite well: https://github.com/rollup/rollup/issues/487

**Comment by dario-piotrowicz** [comment]
Ok this seems to be working quite well:
![Screenshot 2024-12-05 at 11 36 03](https://github.com/user-attachments/assets/57c68d03-8c43-488c-adba-09398c101937)

With it the react development code does get treeshaken away! 🚀

I think this might be the appropriate solution (I can create a PR with this as a followup to #72)

**Comment by jamesopstad** [comment]
Nice! This feels like a weird one because you would expect people to run into this a lot.

**Comment by dario-piotrowicz** [comment]
> Nice! This feels like a weird one because you would expect people to run into this a lot.

yeah I totally agree... 😕 

I even wonder if something like this should be upstreamed in vite itself, isn't replacing `process.env.NODE_ENV` on build a very common behavior? it feels very weird to me that rollup does not do that 😕
